# Generated by Django 3.0.8 on 2020-07-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180330_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='engine_efficiency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='pulsometer_readout',
            field=models.IntegerField(),
        ),
    ]
